【Hackathon No.11】
PaddlePaddle/community pull request #171
Opened 2022-07-07 14:34 UTC by yangguohao

add rfc of MultiMarginLoss

2022-07-08 03:47 UTC, Ligoml commented
你好，请先完成黑客松第二期的任务再参与第三期哦~ https://github.com/PaddlePaddle/Paddle/pull/42364

2022-08-05 13:56 UTC, iclementine commented on rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
> +    - label:Tensor, 维度为[batchsize,1]
不建议有这种形状要求。既然知道第二个维度 size 一定是 1， 那就直接不要这个维度，直接 (batch_size,) 即可。

2022-08-05 13:56 UTC, iclementine commented on rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
> +    - weight: Optional[Tensor],维度为[num_classes,1]
同上

2022-08-05 13:57 UTC, iclementine commented on rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
> +    - reduction:str,'None','mean','sum
建议统一，都用小写字符串。

2022-08-05 14:01 UTC, iclementine requested changes
关于输入的形状和参数，请作为参考。

2022-08-06 12:46 UTC, yangguohao commented on rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
> +    - label:Tensor, 维度为[batchsize,1]
已修改

2022-08-06 12:46 UTC, yangguohao commented on rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
> +    - weight: Optional[Tensor],维度为[num_classes,1]
已修改

2022-08-06 12:46 UTC, yangguohao commented on rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
> +    - reduction:str,'None','mean','sum
已修改

2022-08-08 08:10 UTC, iclementine commented on rfcs/APIs/20220707_api_design_for_multi_margin_loss.md
> +    - reduction:str,'None','mean','sum
'None' 改为小写的 'none'

2022-08-08 08:11 UTC, iclementine approved these changes
LGTM

2022-08-08 09:45 UTC, merged