【Hackathon No.14】为 Paddle 新增 remainder_
PaddlePaddle/community pull request #172
Opened 2022-07-07 17:18 UTC by thunder95

为 Paddle 新增 remainder_

2022-07-11 09:42 UTC, betterpig requested changes

2022-07-11 09:42 UTC, betterpig commented on rfcs/APIs/20220708_api_design_for_remainder_.md
> +- 在 Paddle repo 的 python/paddle/fluid/tests/unittests/test_inplace.py中完成单测代码。
这里改成：
在 Paddle repo 的 python/paddle/fluid/tests/unittests/test_inplace.py 和 python/paddle/fluid/tests/unittests/test_elementwise_mod_op.py中，分别加上 remainder_ 的测试代码。

2022-07-12 00:16 UTC, thunder95 commented on rfcs/APIs/20220708_api_design_for_remainder_.md
> +- 在 Paddle repo 的 python/paddle/fluid/tests/unittests/test_inplace.py中完成单测代码。
@betterpig 已修改

2022-07-12 02:05 UTC, betterpig approved these changes
LGTM

2022-07-12 02:09 UTC, merged