【Hackathon No.26】
PaddlePaddle/community pull request #27
Opened 2022-03-11 17:44 UTC by gsq7474741

为 Paddle 新增 TripletMarginLoss 损失函数API rfc

2022-03-11 18:02 UTC, gsq7474741 commented
@TCChenlong

2022-03-14 03:19 UTC, dingjiaweiww commented
你的 PR 提交成功，感谢你对于开源项目的贡献，请检查 PR 提交格式和内容是否完备，具体请参考[示例](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md)和[模版](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/api_design_template.md)。

2022-03-14 03:19 UTC, dingjiaweiww commented
PR 格式检查通过，你的PR 将接受Paddle 专家以及开源社区的review，请及时关注PR 动态

2022-03-15 03:21 UTC, dingjiaweiww commented
reviewing

2022-03-15 07:31 UTC, shiyutang requested changes
设计文档整体规范可进一步提升，请参考：https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md

2022-03-15 07:31 UTC, shiyutang commented on rfcs/APIs/20220312_api_design_for_TripletMarginLoss.md
> +使paddle支持更多的损失函数
意义可以进一步具体化，比如增加API`xx`，实现xx的功能。

2022-03-15 07:31 UTC, shiyutang commented on rfcs/APIs/20220312_api_design_for_TripletMarginLoss.md
> +torch有此api，是在c++层实现的，不过调用的基础op飞桨均有实现
可以补充完整 torch api 的实现方式，包含关键代码和核心逻辑，从而明确实现原理

2022-03-15 07:31 UTC, shiyutang commented on rfcs/APIs/20220312_api_design_for_TripletMarginLoss.md
> +无此功能，但可以在python层通过调用基础api的形式实现。
可以进一步参考 paddle 其他损失函数 API 实现方式，并对关键逻辑、是否可以复用进行描述

2022-03-15 07:31 UTC, shiyutang commented on rfcs/APIs/20220312_api_design_for_TripletMarginLoss.md
> +且与torch的api一致，方便用户无缝迁移到paddle。
对比分析部分可以阐述不同方案（torch，paddle，numpy，tensorflow等）对于参数设计差异，对参数维度支持差异，特殊场景支持差异等。

2022-03-15 07:31 UTC, shiyutang commented on rfcs/APIs/20220312_api_design_for_TripletMarginLoss.md
> +
实现方案中需要指明关键逻辑步骤，代码存放位置等

2022-03-15 07:31 UTC, shiyutang commented on rfcs/APIs/20220312_api_design_for_TripletMarginLoss.md
> +- 异常检测
测试用例需要进一步具体化

2022-03-17 12:17 UTC, shiyutang requested changes
请按照评审意见进行修改

2022-04-12 02:18 UTC, TCChenlong commented
https://github.com/PaddlePaddle/community/pull/31 merged, this PR is closed, thanks for your contribution!

2022-04-12 02:18 UTC, closed without merging