【Hackathon No.30】
PaddlePaddle/community pull request #28
Opened 2022-03-11 17:56 UTC by gsq7474741

为 Paddle 新增 TripletMarginWithDistanceLoss 损失函数API rfc

2022-03-11 18:02 UTC, gsq7474741 commented
@TCChenlong

2022-03-14 03:19 UTC, dingjiaweiww commented
你的 PR 提交成功，感谢你对于开源项目的贡献，请检查 PR 提交格式和内容是否完备，具体请参考[示例](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md)和[模版](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/api_design_template.md)。

2022-03-14 03:19 UTC, dingjiaweiww commented
PR 格式检查通过，你的PR 将接受Paddle 专家以及开源社区的review，请及时关注PR 动态

2022-03-15 07:36 UTC, shiyutang requested changes
整体格式和上一个PR存在同样问题，故不再赘述，可以参考上一个PR中review意见：https://github.com/PaddlePaddle/community/pull/27/files

2022-04-12 02:20 UTC, closed without merging