【Hackathon No.26】add triplet_margin_loss rfc
PaddlePaddle/community pull request #30
Opened 2022-03-12 14:23 UTC by Ainavo

为 paddle 新增 TripletMarginLoss API

2022-03-14 03:20 UTC, dingjiaweiww commented
你的 PR 提交成功，感谢你对于开源项目的贡献，请检查 PR 提交格式和内容是否完备，具体请参考[示例](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md)和[模版](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/api_design_template.md)。

2022-03-14 03:20 UTC, dingjiaweiww commented
PR 格式检查通过，你的PR 将接受Paddle 专家以及开源社区的review，请及时关注PR 动态

2022-03-15 10:09 UTC, shiyutang requested changes
内容完备，部分说明需要进一步修改

2022-03-15 13:34 UTC, shiyutang requested changes

2022-03-15 13:34 UTC, shiyutang commented on rfcs/APIs/20220312_design_for_triplet_margin_loss.md
> +- 使用场景与功能：Pytorch 实现求解三元组 API 的基本功能，TensorFlow 以训练中的实际参数为代入，两种代码风格不同。功能上基本一致，这里 paddle 三元组 API 的设计将对齐 Pytorch 中的三元组 API。
即说明各个方案的优劣势

2022-03-15 13:43 UTC, shiyutang commented on rfcs/APIs/20220312_design_for_triplet_margin_loss.md
> +
还有更多测试要求，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.html#id1

2022-03-18 15:45 UTC, yangguohao commented
> 内容完备，部分说明需要进一步修改

您好，已根据review comment 修改。请问一下反向传播的正确性验证要自己手写吗，还是有什么框架可以调用。

2022-03-21 09:43 UTC, shiyutang commented
可以继承Optest 并使用内部方法check_grad，具体可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/07_new_op/new_op_cn.html#id6

2022-03-21 09:45 UTC, shiyutang commented
同时你的更改没有看到，请提交更改commit，从而review并合入

2022-04-12 02:19 UTC, TCChenlong commented
https://github.com/PaddlePaddle/community/pull/31 merged, this PR is closed, thanks for your contribution!

2022-04-12 02:19 UTC, closed without merging