[Hackthon No.26]
PaddlePaddle/community pull request #31
Opened 2022-03-13 07:20 UTC by yangguohao

2022-03-14 03:20 UTC, dingjiaweiww commented
你的 PR 提交成功，感谢你对于开源项目的贡献，请检查 PR 提交格式和内容是否完备，具体请参考[示例](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md)和[模版](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/api_design_template.md)。

2022-03-14 03:21 UTC, dingjiaweiww commented
PR 格式检查通过，你的PR 将接受Paddle 专家以及开源社区的review，请及时关注PR 动态

2022-03-15 13:38 UTC, shiyutang commented on rfcs/APIs/ 20220313_api_design_for_tripletmarginloss.md
> +paddle 和 pytorch整体框架相似，故直接采用其方法进行设计。
即两种方案的优劣

2022-03-15 13:38 UTC, shiyutang commented on rfcs/APIs/ 20220313_api_design_for_tripletmarginloss.md
> +参考：[飞桨API 设计及命名规范]
说明可以删除

2022-03-15 13:39 UTC, shiyutang commented on rfcs/APIs/ 20220313_api_design_for_tripletmarginloss.md
> +- `padde.nn.functional.triplet_margin_loss(input, positive, negative, margin=1.0, p=2, epsilon=1e-06, swap=False, reduction='mean', name=None) -> Tensor`
输入和参数支持的维度、参数范围可以进一步说明

2022-03-15 13:39 UTC, shiyutang commented on rfcs/APIs/ 20220313_api_design_for_tripletmarginloss.md
> +
3. 检查 `anchor`、`positive`、`negative` 三者维度是否对齐

2022-03-21 09:48 UTC, shiyutang commented
如果修改完整，请rerequest-review
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/34859558/159237566-577a5925-6120-49b2-a8e5-78844e7bd082.png">

2022-03-22 11:08 UTC, shiyutang requested changes
方案实现细节存在修改部分

2022-03-22 11:08 UTC, shiyutang commented on rfcs/APIs/20220313_api_design_for_tripletmarginloss.md
> +   1. 使用 `paddle.nn.Pairwisedistance` 分别计算得到正锚点与样本和负锚点与样本的距离。
可以替换为 paddle.linalg.norm 底层和nn.PairwiseDistance 调用相同的 pnorm OP，并且可以直接进行函数调用

2022-03-22 11:08 UTC, shiyutang commented on rfcs/APIs/20220313_api_design_for_tripletmarginloss.md
> +                                          positive, 1 or -1 Tensor[float64 or float32],维度为[batch_size,dim]                                                                                           ne
为什么positive和negative需要限制为-1/1的tensor？

2022-03-22 11:08 UTC, shiyutang commented on rfcs/APIs/20220313_api_design_for_tripletmarginloss.md
> +   2. 检查输入的 dtype（含 `input`、`positive`、`negative`）（同其余 functional loss 中的实现）
由于输入损失的tensor不一定为（N，Dim）的形状，还需要对输入进行维度转换

2022-03-23 09:51 UTC, shiyutang approved these changes
LGTM

2022-03-23 09:52 UTC, merged