【Hackathon No.30】
PaddlePaddle/community pull request #34
Opened 2022-03-14 16:59 UTC by yangguohao

Create api_design_for_tripletmargindistanceloss.md

2022-03-15 01:51 UTC, dingjiaweiww commented
你的 PR 提交成功，感谢你对于开源项目的贡献，请检查 PR 提交格式和内容是否完备，具体请参考[示例](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md)和[模版](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/api_design_template.md)。

2022-03-15 01:52 UTC, dingjiaweiww commented
PR 格式检查通过，你的PR 将接受Paddle 专家以及开源社区的review，请及时关注PR 动态

2022-03-15 13:59 UTC, shiyutang requested changes
存在较多需要修正之处，示例可以参考：https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md

2022-03-15 13:59 UTC, shiyutang commented on rfcs/APIs/api_design_for_tripletmargindistanceloss.md
> +需要独立设计实现相关的函数
说明语言可以去除，并且可以对相关替代方式进行说明

2022-03-15 13:59 UTC, shiyutang commented on rfcs/APIs/api_design_for_tripletmargindistanceloss.md
> +>
这部分需要有关键代码和方案分析：https://github.com/pytorch/pytorch/blob/cfb6c942fed64dbb81ccc4f14b2a6650123af2e1/torch/nn/functional.py#L4564
另外tf的方案也可以寻找一下并同样说明

2022-03-15 13:59 UTC, shiyutang commented on rfcs/APIs/api_design_for_tripletmargindistanceloss.md
> +paddle 和 pytorch整体框架相似，故直接采用其方法进行设计。
对比分析需要对比方案和选择原因

2022-03-15 13:59 UTC, shiyutang commented on rfcs/APIs/api_design_for_tripletmargindistanceloss.md
> +
检查输入的维度一致性

2022-03-18 02:19 UTC, TCChenlong requested changes
@yangguohao 已review哈，请按上述描述优化你的RFC，感谢~

2022-03-22 11:13 UTC, shiyutang requested changes
部分实现细节需要修改

2022-03-22 11:13 UTC, shiyutang commented on rfcs/APIs/api_design_for_tripletmargindistanceloss.md
> +   2. 检查输入的 dtype（含 `input`、`positive`、`negative`）（同其余 functional loss 中的实现）
输入损失的不一定为（N，dim），需要检查维度之后进行维度转换

2022-03-22 11:13 UTC, shiyutang commented on rfcs/APIs/api_design_for_tripletmargindistanceloss.md
> +   1. 用户可传入distance_function参数，如果未指定则使用 `paddle.nn.PairWiseDistance` 分别计算得到正锚点与样本和负锚点与样本的距离。
可以替换为paddle.linalg.pnorm

2022-03-22 11:13 UTC, shiyutang commented on rfcs/APIs/api_design_for_tripletmargindistanceloss.md
> +- 5.反向梯度的正确性。
目前已经调整基于python 进行组合的API不需要进行反向梯度的验证

2022-03-23 09:48 UTC, shiyutang approved these changes
LGTM

2022-03-23 09:50 UTC, TCChenlong approved these changes

2022-03-23 09:51 UTC, merged