add 20230228_ppocr_cls_deploy_for_arm
PaddlePaddle/community pull request #396
Opened 2023-03-01 10:36 UTC by Zheng-Bicheng

2023-03-01 10:37 UTC, Zheng-Bicheng commented
修改另一个同学的文件名是因为ppocr有三个模型，他用了ppocr，我这边不好提交新的rfc了。

2023-03-02 02:48 UTC, Zheng-Bicheng commented
@cloud2009 大佬，帮忙request一下arm的姐姐呗

2023-03-02 03:34 UTC, Liliyaw requested changes
Hi 同学调整一下关于任务名称那里的错误说法～

2023-03-02 03:34 UTC, Liliyaw commented on rfcs/AVH/20230228_ppocr_cls_deploy_for_arm.md
> +| 任务名称                                                     | Arm 虚拟硬件上完成 PaddleClas 模型的部署             |
Hi 同学, 任务名称这里忘记更正啦！

2023-03-02 03:59 UTC, Zheng-Bicheng commented on rfcs/AVH/20230228_ppocr_cls_deploy_for_arm.md
> +| 任务名称                                                     | Arm 虚拟硬件上完成 PaddleClas 模型的部署             |
done

2023-03-02 03:59 UTC, Zheng-Bicheng commented
@Liliyaw 修改了哦

2023-03-02 06:19 UTC, onecatcn approved these changes
LGTM

2023-03-02 06:19 UTC, merged