【Hackathon No.24】add RFC for ChannelShuffle
PaddlePaddle/community pull request #40
Opened 2022-03-17 00:37 UTC by BrilliantYuKaimin

增加paddle.nn.ChannelShuffle设计文档。

2022-03-17 02:05 UTC, dingjiaweiww commented
你的 PR 提交成功，感谢你对于开源项目的贡献，请检查 PR 提交格式和内容是否完备，具体请参考[示例](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md)和[模版](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/api_design_template.md)。

2022-03-17 02:05 UTC, dingjiaweiww commented
PR 格式检查通过，你的PR 将接受Paddle 专家以及开源社区的review，请及时关注PR 动态

2022-03-17 12:25 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
请就这两种方案的实现方式的整体逻辑进行分步骤阐述

2022-03-17 12:26 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
请就 torch/tensorflow 两种实现方案进行对比评价和对比分析，论述优势、劣势。

2022-03-17 12:30 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
请对实现方案包含实现文件存放位置，代码内部逻辑进行步骤化的描述

2022-03-17 12:31 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +- 错误检查：`groups`不合法或不整除通道数时能正确抛出异常。
测试内容需要进一步参考这里：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.html#id1

2022-03-17 13:46 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
完成

2022-03-17 13:47 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
> 请就 torch/tensorflow 两种实现方案进行对比评价和对比分析，论述优势、劣势。

完成

2022-03-17 13:47 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
> 请对实现方案包含实现文件存放位置，代码内部逻辑进行步骤化的描述

完成

2022-03-17 13:48 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +- 错误检查：`groups`不合法或不整除通道数时能正确抛出异常。
> 测试内容需要进一步参考这里：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.html#id1

完成

2022-03-18 08:51 UTC, shiyutang requested changes

2022-03-18 08:51 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
此处的对比分析应当对比pytorch 和 tf 两种方案的优劣，此处两种方法差异不大，则可以直接说明分Channel形式来进行和两种方案一致的的设计

2022-03-18 08:51 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +- 前向计算的正确性（与组合API实现比较、与PyTorch比较）；
可以在本地和pytorch实现比较，在test由于CI环境没有pytorch，需要使用 numpy 实现进行比较。

2022-03-18 08:51 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +        pass
这个方法是否需要？

2022-03-18 08:51 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
错误检查：data_format不合法，x不是tensor，x维度检查等

2022-03-18 08:59 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +        pass
其他API均有此方法。

2022-03-18 09:45 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
完成

2022-03-18 09:45 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +- 前向计算的正确性（与组合API实现比较、与PyTorch比较）；
完成

2022-03-18 09:45 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_ChannelShuffle.md
> +
完成

2022-03-23 09:40 UTC, shiyutang approved these changes
LGTM

2022-03-23 09:45 UTC, merged