【Hackathon 4th No.180】在FastDeploy中集成集成地平线推理引擎
PaddlePaddle/community pull request #410
Opened 2023-03-04 05:26 UTC by seyosum

2023-03-04 05:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/community?pullRequest=410) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/community?pullRequest=410) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/community?pullRequest=410) it.</sub>

2023-03-08 07:52 UTC, jiangjiajun commented
@Zheng-Bicheng 麻烦必城帮忙Review下

2023-03-08 08:33 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +5. 分类模型验证正确性
这里为啥要有个分类模型验证准确性呀？是说先移植一个分类模型看看对不对吗？

2023-03-08 08:39 UTC, Zheng-Bicheng requested changes
您好，有一些小问题，麻烦您看一下，做一下针对性的修改。

2023-03-08 08:39 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +5. 分类模型验证正确性
这里为什么要有一个分类模型验证准确性啊，是说先移植分类模型再移植PPYOLO-E吗？

2023-03-08 08:39 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +6. 编写PP-YOLOE前后处理
为什么需要修改preprocess?这里是有什么不能用的算子导致需要修改后处理吗？

2023-03-08 08:39 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +将地平线推理引擎接入FastDeploy，开发HorizonBackends部分，同时针对PP-YOLOE开发对应的前后处理部分。
这里PPYOLOE的前后处理已经开发完了，有什么需求需要重新编写前后处理吗？

2023-03-08 08:39 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +| 提交作者<input type="checkbox" class="rowselector hidden">   | 晴天                             |
这里建议用您的GithubID

2023-03-08 08:39 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +为地平线芯片模型推理提供成熟API，提高开发者开发效率。
这里可以改为为FastDeploy增添地平线推理引擎，提高开发者开发效率。开发者基本上是接触不到你写的backend的，因此并没有提供成熟API一说。

2023-03-08 09:25 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +5. 分类模型验证正确性
分类模型一般情况下是可以直接通过网络输出结果的，因此，为了验证模型推理部分的正确性，所以先移植分类模型，之后再移植PPYOLO-E

2023-03-08 09:36 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +将地平线推理引擎接入FastDeploy，开发HorizonBackends部分，同时针对PP-YOLOE开发对应的前后处理部分。
同上

2023-03-08 09:36 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +| 提交作者<input type="checkbox" class="rowselector hidden">   | 晴天                             |
好的

2023-03-08 09:37 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +为地平线芯片模型推理提供成熟API，提高开发者开发效率。
好的，感谢！

2023-03-08 09:47 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +为地平线芯片模型推理提供成熟API，提高开发者开发效率。
@Zheng-Bicheng 辛苦大佬再帮忙review下吧

2023-03-08 09:56 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +5. 分类模型验证正确性
那你的意思是先在FastDeploy上移植Clas模型随后移植PPYOLOE是吗？

2023-03-08 09:57 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +5. 分类模型验证正确性
对

2023-03-08 09:58 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +6. 编写PP-YOLOE前后处理
* FastDeploy编写了对应的可视化代码，详情可以看一下PaddleDetection的demo，能够直接得到可视化后的图片。
* 如果只是NMS不支持，可以裁剪掉NMS后的部分。这部分我已经实现了，你无需修改后处理代码，可以参考PaddleDetection下RKNPU2 Demo的实现。

2023-03-08 10:01 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +6. 编写PP-YOLOE前后处理
好，我之后参考下！

2023-03-08 10:02 UTC, Zheng-Bicheng requested changes
还有些小问题哈，再修改下

2023-03-08 10:02 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +# 名词解释
这里如果没有名词解释和参考资料可以直接删除

2023-03-08 10:02 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +# 名词解释
好，这块我再修改下

2023-03-08 10:02 UTC, Zheng-Bicheng commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +6. 编写PP-YOLOE前后处理
这里应该是不需要移植前后处理的，把相关部分删除一下吧

2023-03-08 10:13 UTC, seyosum commented on rfcs/FastDeploy/20230303_horizon_for_FastDeploy.md
> +# 名词解释
@Zheng-Bicheng 大佬有空再帮忙review下吧

2023-03-08 13:22 UTC, Zheng-Bicheng approved these changes
LGTM

2023-03-08 13:23 UTC, Zheng-Bicheng commented
@jiangjiajun 我这边没啥问题了。

2023-03-10 05:59 UTC, jiangjiajun approved these changes

2023-03-10 05:59 UTC, merged