【Hackathon No.29】add RFC for PixelUnshuffle
PaddlePaddle/community pull request #43
Opened 2022-03-17 08:29 UTC by thunder95

增加paddle.nn. PixelUnshuffle设计文档。

2022-03-17 08:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/community?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/community?pullRequest=43) before we can accept your contribution.<br/><hr/>**Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/community?pullRequest=43) it.</sub>

2022-03-17 08:33 UTC, thunder95 commented
already signed

2022-03-17 12:46 UTC, shiyutang requested changes
方案整体完备，但是实现细节等需要步骤化说明，请修改方案后再提交代码。修改示例参照：https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md

2022-03-17 12:46 UTC, shiyutang commented on rfcs/APIs/20200317_api_design_for_PixelUnshuffle.md
> +其中的`F.channel_shuffle`是由C++实现的，主要代码为：
这部分有笔误

2022-03-17 12:46 UTC, shiyutang commented on rfcs/APIs/20200317_api_design_for_PixelUnshuffle.md
> +
这部分需要增加tf的实现逻辑和两个方案的逻辑步骤化描述

2022-03-17 12:46 UTC, shiyutang commented on rfcs/APIs/20200317_api_design_for_PixelUnshuffle.md
> +
需要进行方案优劣对比分析

2022-03-17 12:46 UTC, shiyutang commented on rfcs/APIs/20200317_api_design_for_PixelUnshuffle.md
> +
需要对文件存放位置和具体逻辑进行描述

2022-03-17 12:46 UTC, shiyutang commented on rfcs/APIs/20200317_api_design_for_PixelUnshuffle.md
> +- 错误检查：`downscale_factor`不合法或不整除通道数时能正确抛出异常。
测试情况需要丰富化，请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.html#id1

2022-03-21 07:24 UTC, dingjiaweiww commented
你好，我们发现你的设计文档中部分内容与另一个开发者的pr（#44）有雷同现象，pr（#44） 先于你提交，从遵守开源规则、维护有序开源生态的角度出发，你可以基于其他开发者的pr 进行commit修改，不建议再次提交个人pr，因此我们会优先review pr（#44），感谢你对飞桨的贡献！

2022-04-12 02:20 UTC, closed without merging