【Hackathon No.29】add RFC for PixelUnshuffle
PaddlePaddle/community pull request #44
Opened 2022-03-17 10:12 UTC by BrilliantYuKaimin

增加paddle.nn.PixelUnshuffle设计文档。

2022-03-17 12:40 UTC, shiyutang requested changes
方案整体完备，但是实现细节等需要步骤化说明，请修改方案后再提交代码。修改示例参照：https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md

2022-03-17 12:40 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +```
这部分可以放在飞桨现状

2022-03-17 12:40 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
这部分需要修改，请参考这个PR中描述：https://github.com/PaddlePaddle/community/pull/40

2022-03-17 12:40 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
这部分需要修改，请参考这个PR中描述：https://github.com/PaddlePaddle/community/pull/40

2022-03-17 12:40 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +无论是C++实现还是组合API实现，其逻辑都是十分简单的，故考虑使用C++编写新的算子以期取得更高的效率。
这部分需要修改，请参考这个PR中描述：https://github.com/PaddlePaddle/community/pull/40

2022-03-17 12:40 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +```
这部分需要增加内容，请参考这个PR中描述：https://github.com/PaddlePaddle/community/pull/40

2022-03-17 13:49 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +```
> 这部分可以放在飞桨现状

完成

2022-03-17 13:49 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
> 这部分需要修改，请参考这个PR中描述：#40

完成

2022-03-17 13:49 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
> 这部分需要修改，请参考这个PR中描述：#40

完成

2022-03-17 13:49 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +无论是C++实现还是组合API实现，其逻辑都是十分简单的，故考虑使用C++编写新的算子以期取得更高的效率。
> 这部分需要修改，请参考这个PR中描述：#40

完成

2022-03-17 13:49 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +```
> 这部分需要增加内容，请参考这个PR中描述：#40

完成

2022-03-18 09:05 UTC, shiyutang requested changes
参考https://github.com/PaddlePaddle/community/pull/40 进行同步修改

2022-03-18 09:05 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
需要进一步增加对torch方案的步骤化描述

2022-03-18 09:05 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +- 前向计算的正确性（与组合API实现比较、与PyTorch比较）；
本地torch，CI中使用numpy实现的算法进行对比

2022-03-18 09:05 UTC, shiyutang commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
错误检查：输入维度，downscale_factor > 0等

2022-03-18 09:57 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
完成

2022-03-18 09:57 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +- 前向计算的正确性（与组合API实现比较、与PyTorch比较）；
完成

2022-03-18 09:58 UTC, BrilliantYuKaimin commented on rfcs/APIs/20220317_api_design_for_PxielUnshuffle.md
> +
完成

2022-03-22 11:50 UTC, shiyutang approved these changes
LGTM

2022-03-22 11:50 UTC, merged

2022-03-22 12:03 UTC, shiyutang commented
实现内容可以存放在paddle/phi/kernels/cpu(gpu)/ 下，注册则在fluid/oprerator下。如下图所示：
<img width="582" alt="以TraceOp为例：" src="https://user-images.githubusercontent.com/34859558/159477626-f4711b45-8896-4611-9f3d-853e6555eed8.png">
c++ op开发方式可以参见开发指南：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/new_cpp_op_cn.html

2022-03-22 12:04 UTC, shiyutang commented
请对文档中的实现内容位置进行删除或者对应修改

2022-03-22 12:15 UTC, BrilliantYuKaimin commented
> 请对文档中的实现内容位置进行删除或者对应修改

因为cpu和gpu的kernel是一样的，所以参考pixel_shuffle把实现放在`paddle/phi/kernels/impl/pixel_unshuffle_kernel_impl.h`中。

2022-03-23 09:39 UTC, shiyutang commented
如果实现和设备无关，应当放在kernel根目录下，如下所示：
<img width="752" alt="image" src="https://user-images.githubusercontent.com/34859558/159669261-d14aab33-ae80-4a1b-842e-01f0d2a74d67.png">

<img width="881" alt="image" src="https://user-images.githubusercontent.com/34859558/159669143-0b524738-b3e8-49ca-af65-99b0e7efadc8.png">

2022-03-23 09:40 UTC, shiyutang commented
请提交一个新的PR对相应内容进行修改