【Hackathon 4th No.84】为神经网络编译器 CINN 增加 ReverseComputeInline 原语
PaddlePaddle/community pull request #465
Opened 2023-03-16 07:57 UTC by zrr1999

题目：https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A0%B8%E5%BF%83%E6%A1%86%E6%9E%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%20CINN%20%E5%BC%80%E5%8F%91%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task84

参考资料：
1. [CINN项目贡献指南](https://github.com/PaddlePaddle/CINN/pull/810)  
2. [CINN IR抽象语法树](https://github.com/PaddlePaddle/CINN/pull/775)  
3. [CINN调度原语开发](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/CINN/CINN_ir_schedule.md)

2023-03-22 11:21 UTC, CtfGo requested changes

2023-03-22 11:21 UTC, CtfGo commented on rfcs/CINN/APIs/20230316_cinn_api_design_reverse_compute_inline.md
> +      auto it = self_->idx_sub_.find(var);
不要直接贴一大段源码，给链接就行，可以概要介绍一下TVM里RerverseComputeInline的关键实现思路和流程

2023-03-22 11:21 UTC, CtfGo commented on rfcs/CINN/APIs/20230316_cinn_api_design_reverse_compute_inline.md
> +支持新增原语 Trace 重放：在 cinn/ir/schedule_desc.cc 中使用CINN_BUILD_STEP_KIND 注册 ComputeInline 原语的重放函数
```suggestion
## API实现方案
ReverseComputeInline 原语：分别添加接口及实现至 cinn/ir/ir_schedule.h、cinn/ir/ir_schedule.cc
支持新增原语 Trace 重放：在 cinn/ir/schedule_desc.cc 中使用CINN_BUILD_STEP_KIND 注册 ReverseComputeInline 原语的重放函数
```

2023-03-28 11:50 UTC, zrr1999 commented on rfcs/CINN/APIs/20230316_cinn_api_design_reverse_compute_inline.md
> +      auto it = self_->idx_sub_.find(var);
好的，这里我改成了tvm代码注释里的步骤过程。

2023-04-02 12:42 UTC, zrr1999 commented on rfcs/CINN/APIs/20230316_cinn_api_design_reverse_compute_inline.md
> +## API实现方案
好的，已经加入了伪代码

2023-04-03 02:07 UTC, CtfGo commented on rfcs/CINN/APIs/20230316_cinn_api_design_reverse_compute_inline.md
> +ComputeInline 原语单测添加至 cinn/backends/ir_schedule_test.cc
```suggestion
ReverseComputeInline 原语单测添加至 cinn/backends/ir_schedule_test.cc
```

2023-04-04 10:33 UTC, zrr1999 commented on rfcs/CINN/APIs/20230316_cinn_api_design_reverse_compute_inline.md
> +ComputeInline 原语单测添加至 cinn/backends/ir_schedule_test.cc
好的，这部分已经修改

2023-04-06 02:03 UTC, CtfGo approved these changes
LGTM

2023-04-06 02:03 UTC, merged