【Hackathon No.23】
PaddlePaddle/community pull request #50
Opened 2022-03-18 13:05 UTC by Asthestarsfalll

为 Paddle 新增 Softmax2D 组网API

2022-03-21 11:11 UTC, shiyutang requested changes
整体代码完整，部分细节需要调整，建议参考：https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20200301_api_design_for_quantile.md

2022-03-21 11:11 UTC, shiyutang commented on rfcs/APIs/20220318_api_design_for_nn_Softmax2D.md
> +
增加覆盖CPU和GPU的测试场景；

2022-03-21 13:05 UTC, Asthestarsfalll commented
已全部修改

2022-03-22 11:24 UTC, shiyutang approved these changes
LGTM

2022-03-22 11:24 UTC, merged