Add meeting agenda in ppsigs
PaddlePaddle/community pull request #557
Opened 2023-06-28 11:32 UTC by KevinLi43

2023-06-28 11:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/community?pullRequest=557) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/community?pullRequest=557) before we can accept your contribution.<br/><hr/>**lihaoxuan04** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/community?pullRequest=557) it.</sub>

2023-06-28 11:34 UTC, onecatcn approved these changes
LGTM

2023-07-03 06:28 UTC, shiyutang requested changes
可以根据上述修改，并进一步补充参与人的list

2023-07-03 06:28 UTC, shiyutang commented on ppsigs/meetings/2023/2023-07-04-meeting-agenda.md
> +* 会议时间：2023-07-04
* 会议时间：2023-7-04 19：00

2023-07-03 06:28 UTC, shiyutang commented on ppsigs/meetings/2023/2023-07-04-meeting-agenda.md
> +  * 腾讯会议
* 腾讯会议：411-8645-4113

2023-07-03 06:28 UTC, shiyutang commented on ppsigs/meetings/2023/2023-07-04-meeting-agenda.md
> +* 本次参会member list：
* 本次拟参会member list：

2023-07-03 06:28 UTC, shiyutang commented on ppsigs/meetings/2023/2023-07-04-meeting-agenda.md
> +
根据contributor infor链接中统计的开发者

2023-07-03 06:28 UTC, shiyutang commented on ppsigs/meetings/2023/2023-07-04-meeting-agenda.md
> +* 下次会议召开时间和议题预告
* 每个人一句话的自我介绍（5 mins）：活动经历，接触飞桨的经历，对我们活动的期待等等。
* 介绍 Issue 攻关活动（5 mins）
* 飞桨OCR套件的RD进行OCR代码解析技术分享，大家自由提问（30mins）：
    * [andyjpaddle](https://github.com/andyjpaddle) 
* 过Issue，有哪些回复好的issue，哪些尚未通过的issue，基于Issue提交代码的例子（10mins）
     * [marshall-dteach](https://github.com/marshall-dteach)：https://github.com/PaddlePaddle/PaddleSeg/issues/3138 
     * [livingbody](https://github.com/livingbody)：https://github.com/PaddlePaddle/PaddleOCR/issues/10205
     * [Asthestarsfalll](https://github.com/Asthestarsfalll)：https://github.com/PaddlePaddle/PaddleSeg/issues/3345
* 自由发言，可以提需求给大家讨论、提问等（10 minutes）
* 确定下次的部分议题、召开时间（3 mins）
   * PPOCR的科普向分享，涵盖全流程三大方向。

2023-07-03 07:16 UTC, shiyutang requested changes
两处细节～

2023-07-03 07:16 UTC, shiyutang commented on ppsigs/meetings/2023/2023-07-04-meeting-agenda.md
> +
仿照PFCC的，第一排不放人，另外可以加一下链接：
<img width="966" alt="image" src="https://github.com/PaddlePaddle/community/assets/34859558/a00c82ee-6606-4714-8462-12b6e2530a06">

2023-07-03 07:16 UTC, shiyutang commented on ppsigs/meetings/2023/2023-07-04-meeting-agenda.md
> +* 本次拟参会member list（根据contributor infor链接中统计的开发者）：
删去“（根据contributor infor链接中统计的开发者）”

2023-07-03 07:49 UTC, shiyutang commented
[ppsigs/meetings/2023/2023-07-04-meeting-agenda.md](https://github.com/PaddlePaddle/community/pull/557/files#diff-19567ef30b185861ed791b282ef60d724317294fe7cfbcdd022f8abdd314550d)需要修改成0705，另外minutes可以不用增加，我已经增加并合入了～

2023-07-03 07:53 UTC, shiyutang approved these changes
LGTM

2023-07-03 07:53 UTC, merged