【Hackathon No.29】 新增 PixelUnshuffle API 设计文档
PaddlePaddle/community pull request #60
Opened 2022-03-22 12:41 UTC by BrilliantYuKaimin

增加了PixelUnshuffle API 设计文档。

2022-03-23 09:44 UTC, shiyutang commented
新增文档正确，请讲之前的文档进行删除，即下图所示文件名
<img width="896" alt="image" src="https://user-images.githubusercontent.com/34859558/159670274-087457dc-be65-4570-b520-ce318e1cd29b.png">

2022-03-23 09:46 UTC, shiyutang requested changes
本文档已经完善，需要进一步删除之前的文档

2022-03-23 10:59 UTC, BrilliantYuKaimin commented
> 本文档已经完善，需要进一步删除之前的文档

不是已经被revert了吗？

2022-03-23 11:32 UTC, shiyutang commented
没有revert成功，可以直接删除

2022-03-23 11:46 UTC, BrilliantYuKaimin commented
> 没有revert成功，可以直接删除

完成

2022-03-24 03:16 UTC, shiyutang approved these changes
LGTM

2022-03-24 03:16 UTC, merged