【Hackathon 5th No.63】PhyCRNet: Physics-informed Convolutional-Recurrent Network for Solving Spatiotemporal PDEs
PaddlePaddle/community pull request #676
Opened 2023-09-28 23:43 UTC by co63oc

2023-10-15 07:57 UTC, HydrogenSulfate requested changes
1. RFC内容过于简单，可以参考其他选手的RFC https://github.com/PaddlePaddle/community/pull/683/files 完善各部分内容
2. 一个RFC对应一个PR，不能提交

2023-10-15 12:02 UTC, co63oc commented
> 1. RFC内容过于简单，可以参考其他选手的RFC https://github.com/PaddlePaddle/community/pull/683/files 完善各部分内容
> 2. 一个RFC对应一个PR，不能提交

已修改为No.63，增加RFC内容

2023-11-13 03:05 UTC, wangguan1995 reviewed
Need fix

2023-11-13 03:05 UTC, wangguan1995 commented on rfcs/Science/20230929_phycrnet.md
> +
![image](https://github.com/PaddlePaddle/community/assets/39621324/791b5bb8-8861-4de2-bf46-91ece2a24ec5)

需要完成的模块包括：
- 蓝色的物理损失函数模块
- BC encoding模块
- FD based filter微分模块
- 网络Encoder, Decoder模块
- CRNN卷积层：LSTM算法

2023-11-13 03:05 UTC, wangguan1995 commented on rfcs/Science/20230929_phycrnet.md
> +在此，我们考虑一组多维 (n)、非线性、耦合的参数设置下的偏微分方程 (PDE) 系统的通用形式：
对于物理损失模块：
在此，我们考虑一.....

2023-11-13 03:05 UTC, wangguan1995 commented on rfcs/Science/20230929_phycrnet.md
> +PaddleScience 套件暂无 PhyCRNet 模型案例。
缺少 FD filter 计算差分模块
缺少 LSTM 相关算法
缺少 Burgers equation & FitzHugh-Nagumo reaction-diffusion equations 的算例、数据集和方程

2023-11-13 03:05 UTC, wangguan1995 commented on rfcs/Science/20230929_phycrnet.md
> +原代码使用脚本 Codes/PhyCRNet_burgers.py 运行，复现需要达到原有代码精度，并使用 PaddleScience 复现
完成https://github.com/isds-neu/PhyCRNet/blob/main/README.md所示部分，复现需要达到原有代码精度，使用PaddleScience复现

2023-11-21 11:51 UTC, HydrogenSulfate approved these changes
LGTM

2023-11-21 11:51 UTC, luotao1 approved these changes

2023-11-21 11:51 UTC, merged