【Hackathon 5th No.56】A Physics-Informed Neural Network to solve 2D steady-state heat equation
PaddlePaddle/community pull request #683
Opened 2023-10-06 03:17 UTC by moosewoler

【Hackathon 5th No.56】A Physics-Informed Neural Network to solve 2D steady-state heat equation

2023-10-09 09:41 UTC, HydrogenSulfate requested changes

2023-10-09 09:41 UTC, HydrogenSulfate commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +然后通过深度神经网络对$u(x，y)$进行近似。采用Paddle API的$u(x，y)$定义如下：
使用英文逗号

2023-10-09 09:41 UTC, HydrogenSulfate commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +D = \{(x, y)|-1\leq{x}\leq{+1},-1\leq{y}\leq{+1}\}
`\{` 改为`\\{`，否则无法正常显示

2023-10-09 09:41 UTC, HydrogenSulfate commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +$$
改为
```
$$
\begin{cases}
T(-1, y) = 75.0 ^\circ{C} \\
T(+1, y) = 0.0 ^\circ{C} \\
T(x, -1) = 50.0 ^\circ{C} \\
T(x, +1) = 0.0 ^\circ{C}
\end{cases}
$$
```
否则无法正常换行

2023-10-09 09:41 UTC, HydrogenSulfate commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +由式（1）定义$f(x，y)$为：
使用英文逗号

2023-10-09 09:41 UTC, HydrogenSulfate commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +$u(x，y)$可通过深度神经网络进行近似求解。这个假设与方程（2）一起得出了基于物理信息的神经网络$f(x，y)$。这个网络可以通过对组成函数应用链式规则进行自动微分而导出。
全文检查一下，公式中使用英文逗号

2023-10-09 09:41 UTC, HydrogenSulfate commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +- 202312 ：整理项目产出，撰写案例文档
这个模型看起来比较简单，按照正常模型复现进度，10月20日左右应该能完成基于PaddleAPI的复现，11月初应该能完成基于PaddleScience的复现；11月中旬完成案例文档。可以参考一下这个进度重新写一下排期规划

2023-10-18 07:53 UTC, luotao1 commented
已经有 RFC 合入了，如果需要更新和完善，可以在原来的 RFC 上进行修改，感谢！
-  https://github.com/PaddlePaddle/community/pull/692

2023-10-18 07:53 UTC, closed without merging

2023-10-23 02:56 UTC, moosewoler commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +然后通过深度神经网络对$u(x，y)$进行近似。采用Paddle API的$u(x，y)$定义如下：
已修改

2023-10-23 02:56 UTC, moosewoler commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +D = \{(x, y)|-1\leq{x}\leq{+1},-1\leq{y}\leq{+1}\}
已修改

2023-10-23 02:56 UTC, moosewoler commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +$$
已修改

2023-10-23 02:56 UTC, moosewoler commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +由式（1）定义$f(x，y)$为：
已修改

2023-10-23 02:56 UTC, moosewoler commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +$u(x，y)$可通过深度神经网络进行近似求解。这个假设与方程（2）一起得出了基于物理信息的神经网络$f(x，y)$。这个网络可以通过对组成函数应用链式规则进行自动微分而导出。
已修改

2023-10-23 02:57 UTC, moosewoler commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
> +- 202312 ：整理项目产出，撰写案例文档
受到本职工作影响，此进度过于激进，恐无法完成。

2023-10-23 02:57 UTC, moosewoler commented on rfcs/Science/20230927_science_hackthon5th_56_2D_steady-state_heat_equation.md
已修改