【Hackathon 5th No.56】A Physics-Informed Neural Network to solve 2D steady-state heat equation
PaddlePaddle/community pull request #692
Opened 2023-10-09 12:11 UTC by Gxinhu

Add Hackathon 5th Science 56 RFC

关联：https://github.com/PaddlePaddle/PaddleScience/pull/560

2023-10-16 03:40 UTC, luotao1 commented
科学计算的官方活动群，可以加一下
<img width="300" alt="image" src="https://github.com/PaddlePaddle/community/assets/6836917/c4a3b793-468e-4098-9f24-aa39a6ec57d7">

2023-10-18 06:46 UTC, liaoxin2 requested changes

2023-10-18 07:04 UTC, Gxinhu commented on hackathon/hackathon_5th/20231009_science_56.md
> +\frac{\partial^2T}{\partial x^2} + \frac{\partial^2T}{\partial y^2}=0
> 请全文检查一下，公式中也需要有标点符号

没有理解“公式中也需要有标点符号”是啥意思

2023-10-18 07:16 UTC, liaoxin2 requested changes

2023-10-18 07:16 UTC, liaoxin2 commented on hackathon/hackathon_5th/20231009_science_56.md
> +\frac{\partial^2T}{\partial x^2} + \frac{\partial^2T}{\partial y^2}=0
就是在每一行数学公式后面加上英文逗号或者句号

2023-10-18 07:35 UTC, Gxinhu commented on hackathon/hackathon_5th/20231009_science_56.md
> +\frac{\partial^2T}{\partial x^2} + \frac{\partial^2T}{\partial y^2}=0
> 就是在每一行数学公式后面加上英文逗号或者句号

好的，已添加

2023-10-18 07:36 UTC, Gxinhu commented on hackathon/hackathon_5th/20231009_science_56.md
> +其中，$T$ 表示温度分布，传统的求解方法涉及使用数值方法如有限元法或有限差分法，这些方法通常需要离散化领域并求解大规模矩阵系统。近年来，基于物理信息的神经网络（Physics-informed neural networks, PINN）逐渐成为求解偏微分方程的新方法。PINN 结合了神经网络的灵活性和对物理约束的建模能力，能够直接在连续领域中解决偏微分方程问题。
已修改

2023-10-18 07:46 UTC, liaoxin2 approved these changes

2023-10-18 07:52 UTC, luotao1 approved these changes

2023-10-18 07:52 UTC, merged